language: r
cache: packages
sudo: required
warnings_are_errors: false

os:
  - linux
#  - osx
#  - windows

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - BOOTSTRAP_LATEX=""

before_install:
  - sudo apt-get install aptitude
  - sudo aptitude -y install libgdal-dev 
  - sudo aptitude -y install libproj-dev

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

  
#after_success:
#  - Rscript -e 'covr::codecov()'
 
#  - ./travis-tool.sh install_aptget r-cran-rcpp libquantlib0-dev r-cran-runit r-cran-rgl littler r-cran-shiny
#   - ./travis-tool.sh install_aptget r-cran-rgl r-cran-zoo
#  - ./travis-tool.sh install_r magrittr
#   - ./travis-tool.sh install_r dplyr
#   - ./travis-tool.sh install_r plotKML
#   - ./travis-tool.sh install_r lubridate
#   - ./travis-tool.sh install_r ggplot2
#   - ./travis-tool.sh install_r tidyr

#r_packages:
#  - devtools
#  - rgeos
##  - rgdal
#  - raster
#  - sp
#  - leaflet
#  - shiny
#  - knitr
#  - covr
#  - rmarkdown
#  - testthat
  
#after_success:
#  - Rscript -e 'covr::codecov()'
 
