language: r
cache: packages
sudo: required
warnings_are_errors: false

os:
  - linux
  - osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - BOOTSTRAP_LATEX=""

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

#install:
#  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
#  - Rscript -e "devtools::install_deps(dep = TRUE)"
#  - Rscript -e "devtools::install_github('jimhester/covr')"

r_github_packages:
  - jimhester/covr

r_binary_install:
  - magrittr
  - dplyr
  - XML

after_success:
  - Rscript -e 'library(covr); codecov()'
  
