codecov:
  token: cdd9ea62-df9d-4bfa-8e65-b7d241ea123c
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "20...100"

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default